Add configuration method to decide what existing data to compare
SalesLoft/rspec-rcv pull request #7
Opened 2016-09-23 17:49 UTC by lumenlunae

Hello! I found this useful, don't know if it fits with your design or not. I use the codec to remove the "recorded_at" and "file" properties of the json and move the data into the json root. However, when  I do the comparison, it will always return saying there was a difference because the current code is looking for the "data" property and my json doesn't have it.

This adds a configuration method "parse_existing" to decide what existing data actually gets compared. Thanks!

2016-09-23 17:50 UTC, sb8244 commented on lib/rspec-rcv/handler.rb
> +        existing_data_comparison = opts[:parse_existing].call(existing_data)
Can this be `fetch` in order to ensure it's always present?

2016-09-23 17:50 UTC, sb8244 requested changes
Nice! I'm good with this with the small fetch change.

2016-09-23 17:51 UTC, sb8244 commented
Thanks @lumenlunae! I like the change. It does fit well with the objective with having a stable base that can be extended.

2016-09-23 17:59 UTC, lumenlunae commented
Realized I don't have any specs for it, but adding some minor ones now. Thanks! :D

> On Sep 23, 2016, at 10:51 AM, Stephen Bussey <notifications@github.com> wrote:
> 
> Thanks @lumenlunae! I like the change. It does fit well with the objective with having a stable base that can be extended.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-09-23 18:03 UTC, lumenlunae commented
Eep sorry for clouding the master branch. I was in a bit of a rush on my own project.

2016-09-24 01:36 UTC, sb8244 approved these changes

2016-09-24 01:37 UTC, sb8244 commented
I'll merge this in when I'm not on a Windows machine. I'll leave it open until then so I don't forget!

Thanks for the contribution.

2016-09-24 17:05 UTC, merged

2016-09-24 17:08 UTC, sb8244 commented
Deployed in 0.3.2 https://github.com/SalesLoft/rspec-rcv/tree/v0.3.2